### PR TITLE
Fix wind sometimes not working

### LINKED ISSUE #25: The wind texture is sometimes never loaded
## Describe the bug
In `prepare_uniform_buffers`, we exit early if `RegionConfiguration` did not change. However, we might have set `FallbackImage` before as the wind texture if the correct one didn't load yet! This means that if in the first frame we set the fallback image, we never change it. 

## To Reproduce
Open an example a bunch of times. Sometimes the wind does not trigger.

## Expected behavior
Wind should always work once the texture was loaded

## Additional context
A simple `mut loaded: Local<bool>` could be used as a hacky way to fix this.

### PR DESCRIPTION
**Pull request by janhohenheim**
Fix #25

### CODE REVIEW

**Comment by janhohenheim** [comment]
@EmiOnGit do you have a better idea for a fix?

**Comment by EmiOnGit** [comment]
See #25

**Comment by EmiOnGit** [comment]
I just noticed something else. If someone swaps between multiple noise textures (maybe one "stormy" and one "calm" texture), the same issue could occur since the local loaded would stay true

**Comment by janhohenheim** [comment]
Good catch, fixed it

**Pull request merged**
