### PR TITLE
Fix alignment issue on Wasm

### LINKED ISSUE #21: Support Wasm
## What problem does this solve or what need does it fill?
I'd like to use grass in Wasm builds :D

## Describe the solution you'd like
Feature parity on Wasm. Should be technically possible, since we don't use compute shaders.

## Describe alternatives you've considered
Just support native

## Additional context
Checking this by hand, I notice that the first issue is that a struct passed to the shader is currently not 16 byte aligned

### PR DESCRIPTION
**Pull request by janhohenheim**
Fix #21 
image

### CODE REVIEW

**Comment by EmiOnGit** [comment]
This looks amazing!
I'm currently not at my computer. Have you checked all examples?

**Comment by EmiOnGit** [comment]
Btw Jan do you mind if I just give you rights to merge?
You're trustworthy enough :)

**Comment by janhohenheim** [comment]
hehe, sure, thanks :)
I'm testing them right now. `PresentMode::Immediate` doesn't work in Wasm and thus has to be removed for testing, but that's not a library issue.

**Comment by janhohenheim** [comment]
All examples except `load_from_file` work, but that one doesn't work on native and the `master` branch for me either:
`thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/render/draw_mesh.rs:41:65` that would be this line:
```rust
pass.set_bind_group(2, chunk.uniform_bindgroup.as_ref().unwrap(), &[]);
```
Seeing as this is not a regression, I'm merging this PR.

**Comment by EmiOnGit** [comment]
Go for it! :1st_place_medal:

**Pull request merged**
