### PR TITLE
Optimize prepare stage for frames that did not change

### PR DESCRIPTION
**Pull request by janhohenheim**
Disclaimer: I don't know how much impact this actually has on the performance.

### CODE REVIEW

**Comment by EmiOnGit** [comment]
Actually this has a pretty good! :)
If you actually want you can optimize it even more by splitting the function into two functions.
One that is just preparing the uniform buffers [prepare_uniform_buffers] 
and one just for the instance buffer [prepare_instance_buffer]
They should be independent, but beside that it would be also more organized.
However, you don't have to ofc.

**Comment by janhohenheim** [comment]
I see what you mean, but wouldn't they both have mut access to `GrassCache` and thus not run in parallel?

**Comment by EmiOnGit** [comment]
> ah, but they could have other early return guards, I see!

The other return guards doesn't matter as much because these 2 functions are the only two that could run in parallel 
(The only in the `RenderStage::Prepare` at least currently) 
This means we'd need to split the buffers in separate resources or use unsafe code. 
I'm against the second option and unsure about the first

**Comment by EmiOnGit** [comment]
It is definitely better readable though

**Comment by janhohenheim** [comment]
How about this for the moment? This way, we at least distinguish the cases of config changed vs grass changed

**Comment by EmiOnGit** [comment]
Ah also the functions are named the wrong way around. `prepare_instance_buffer` is currently preparing all uniform buffers :smile:

**Comment by janhohenheim** [comment]
hehehe, good catch. Fixed.

**Comment by EmiOnGit** [comment]
Nice, looks almost good now. If you simplify the for loop mentioned above I'll merge.
Have you looked into the issues btw?

**Comment by janhohenheim** [comment]
Which loop did you mention? Do you mean like this? 
Checking the issues now 👍

**Comment by EmiOnGit** [comment]
Yes now it's perfect

**Pull request merged**
